export * from "@/pages/dashboard/VehicleCounting";
export * from "@/pages/dashboard/InputEndpoint";
export * from "@/pages/dashboard/CrackDetection";
export * from "@/pages/dashboard/AnomalyDetection";
export * from "@/pages/dashboard/PenangkapanIkanTerukur";
export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
